# Server
host: 0.0.0.0
port: 80

# Security
jwt_secret: change-me-to-a-random-string
users:
    admin: change-me

# Docker Hosts
docker_hosts:
    default: local
    hosts:
        local:
            driver: socket
            endpoint: /var/run/docker.sock
            mount_points:
                docker:
                    path: /opt/docker
                    read_only: false
