root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  entrypoint = ["./tmp/main"]
  full_bin = "BOXBOX_DEV_MODE=true ./tmp/main"
  include_dir = ["internal", "cmd"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "frontend", "node_modules"]
  delay = 5000
  stop_on_error = true
  kill_delay = "2s"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
